### ISSUE TITLE
Suggestion using the UDF

### ISSUE THREAD

**Issue by riomario1** [edwardcapriolo/hive_test#13]
I would like to use hive UDF to find geo information (city, zip etc) from ip address. 

I was routed to this UDF by Edward (https://github.com/edwardcapriolo/hive-geoip/issues/1)

Could someone help me since I am stuck in creating Hive geo udf for more than a week.

If this is not the right right udf, please guide me some guidance.

I am getting error message when I try to create temporary function.

Below are the steps:

hive> add jar hive-exec-0.11.0.jar;
Added hive-exec-0.11.0.jar to class path
Added resource: hive-exec-0.11.0.jar
hive> add jar geo-ip-java.jar;
Added geo-ip-java.jar to class path
Added resource: geo-ip-java.jar
hive> add jar hiveunit-0.0.4-SNAPSHOT.jar;
Added [hiveunit-0.0.4-SNAPSHOT.jar] to class path
Added resources: [hiveunit-0.0.4-SNAPSHOT.jar]
hive> add file  GeoIP.dat;
Added resource: GeoIP.dat
hive> create temporary function geoip as 'com.jointhegrid.hive.udf.GenericUDFGeoIP';
FAILED: Class com.jointhegrid.hive.udf.GenericUDFGeoIP not found
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.FunctionTask

I am following up from Git:
https://github.com/edwardcapriolo/hive-geoip

Thank you!

**Comment by bobfreitas** [comment]
I had similar problems with hive_test, so I started over with Hive 1.1.0 and Hadoop 2.6.0, and worked through the source code to extract the needed testing classes, much like what Edward did.  It got it to work for testing a custom UDAF that I wrote.  

Hopefully, it will work for you, https://github.com/bobfreitas/hiveunit-mr2.

Good Luck!
